# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/splashscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SplashScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropOutShadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dropOutShadowFrame.setFont(font)
        self.dropOutShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(166, 160, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}")
        self.dropOutShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropOutShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropOutShadowFrame.setObjectName("dropOutShadowFrame")
        self.appName = QtWidgets.QLabel(self.dropOutShadowFrame)
        self.appName.setGeometry(QtCore.QRect(0, 80, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(32)
        self.appName.setFont(font)
        self.appName.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.appDesc = QtWidgets.QLabel(self.dropOutShadowFrame)
        self.appDesc.setGeometry(QtCore.QRect(0, 140, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.appDesc.setFont(font)
        self.appDesc.setStyleSheet("color: rgb(85, 85, 127);")
        self.appDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.appDesc.setObjectName("appDesc")
        self.progressBar = QtWidgets.QProgressBar(self.dropOutShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(120, 230, 421, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border: 2px solid  rgb(85, 85, 127);\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.278, y1:0.181818, x2:1, y2:1, stop:0  rgba(200,190 , 127,255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.loading = QtWidgets.QLabel(self.dropOutShadowFrame)
        self.loading.setGeometry(QtCore.QRect(0, 260, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(8)
        self.loading.setFont(font)
        self.loading.setStyleSheet("color: rgb(85, 85, 127);")
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.verticalLayout.addWidget(self.dropOutShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appName.setText(_translate("MainWindow", "<strong>YT</strong>DOWNLOADER"))
        self.appDesc.setText(_translate("MainWindow", "<html><head/><body><p>Download Youtube Videos and Playlists</p></body></html>"))
        self.loading.setText(_translate("MainWindow", "<html><head/><body><p>Loading.....</p></body></html>"))
